apiVersion: v1
kind: Secret
metadata:
  name: quay-io-credentials
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJZbkpoZFc1cmFXMDRPQ3R4ZFdGNVgybHZYMk55WldSbGJuUnBZV3h6T2xBMlR6bEhVVFpUVGtKWVVWQlBSRGhRU1ZWS1QwTkZSbEF4UkVwQ016WkdWamN3V2sxQ1NVWldVVFE0T1VSTVUwSkJPVWcyT0RZMlMxTkdTMUE1TWtJPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson