apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment
spec:
  steps:
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: retrieve-yaml
      resources: {}
      script: |
        echo $(pwd)
        cd /workspace
        mkdir k8s
        cd k8s
        echo $(pwd)
        curl https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml > run-steps-as-non-root.yaml
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: extract-task
      resources: {}
      script: |
        echo $(pwd)
        cd /workspace/k8s
        echo $(pwd)
        head -n 24 run-steps-as-non-root.yaml > run-steps-as-non-root-task-only.yaml
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: swap-image
      resources: {}
      script: |
        echo $(pwd)
        cd /workspace/k8s
        sed 's/ubuntu/quay.io\/ibmgaragecloud\/alpine-curl/g' run-steps-as-non-root-task-only.yaml > run-steps-as-non-root-alpine-task.yaml
        cat run-steps-as-non-root-alpine-task.yaml
  




