HTTP/2 200 
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: "63f62f8f4119b7b1b017a8750f5a566f25aa58c077932d4d10f42bf19a7e49d8"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 61B0:0332:A205B2:B7261E:610F7160
accept-ranges: bytes
date: Sun, 08 Aug 2021 06:26:52 GMT
via: 1.1 varnish
x-served-by: cache-itm18830-ITM
x-cache: HIT
x-cache-hits: 1
x-timer: S1628404013.537597,VS0,VE1
vary: Authorization,Accept-Encoding
access-control-allow-origin: *
x-fastly-request-id: 0c914a6b791a6adaa8192a8897e1dacfa368c8a9
expires: Sun, 08 Aug 2021 06:31:52 GMT
source-age: 33
content-length: 751

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-non-root-steps
spec:
  steps:
    # no securityContext specified so will use
    # securityContext from TaskRun podTemplate
    - name: show-user-1001
      image: ubuntu
      command:
        - ps
      args:
        - "aux"
    # securityContext specified so will run as
    # user 2000 instead of 1001
    - name: show-user-2000
      image: ubuntu
      command:
        - ps
      args:
        - "aux"
      securityContext:
        runAsUser: 2000
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: show-non-root-steps-run-
spec:
  taskRef:
    name: show-non-root-steps
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
